---
version: '3.5'

networks:
  testnet:
    name: testnet

services:
  ldap:
    container_name: ldap
    image: osixia/openldap:latest
    tty: true
    privileged: true
    stdin_open: true
    ports:
      - 389:389
      - 636:636
    hostname: ldap.testnet
    networks:
      - testnet
    environment:
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_DOMAIN: "example.org"
      LDAP_ORGANISATION: "example"
      LDAP_ADMIN_PASSWORD: "admin"

  phpldapadmin:
    container_name: ldapadmin
    image: osixia/phpldapadmin
    ports:
      - 8443:443
    networks:
      - testnet
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap.testnet"
      LDAP_BASE: "dc=example,dc=org"
      LDAP_LOGIN_DN: "cn=admin,dc=example,dc=org"

  ocis:
    container_name: ocis
    image: owncloud/eos-ocis-dev:latest
    tty: true
    privileged: true
    stdin_open: true
    ports:
      - 9200:9200
      - 9160:9160
      - 9140:9140
    env_file:
      - ./config/eos-docker.env
    hostname: ocis
    networks:
      - testnet
    volumes:
      - .:/ocis
      - ../ocis-reva:/ocis-reva
      - ../reva:/reva
    environment:
      EOS_MGM_URL: ${EOS_MGM_URL:-root://mgm-master.testnet:1094}
      OCIS_DOMAIN: ${OCIS_DOMAIN:-localhost}
      KONNECTD_ISS: https://${OCIS_DOMAIN:-localhost}:9200
      KONNECTD_LOG_LEVEL: debug
      KONNECTD_TLS: '0'
      PHOENIX_OIDC_AUTHORITY: https://${OCIS_DOMAIN:-localhost}:9200
      PHOENIX_OIDC_METADATA_URL: https://${OCIS_DOMAIN:-localhost}:9200/.well-known/openid-configuration
      PHOENIX_WEB_CONFIG_SERVER: https://${OCIS_DOMAIN:-localhost}:9200
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      REVA_OIDC_ISSUER: https://${OCIS_DOMAIN:-localhost}:9200
      OCIS_LOG_LEVEL: debug
      REVA_TRANSFER_EXPIRES: 86400
      REVA_STORAGE_EOS_DRIVER: eoshome
      REVA_STORAGE_EOS_DATA_DRIVER: eoshome
      REVA_STORAGE_EOS_NAMESPACE: "/eos/dockertest/reva/users"
      REVA_STORAGE_EOS_MASTER_URL: ${EOS_MGM_URL:-root://mgm-master.testnet:1094}
      REVA_STORAGE_EOS_SLAVE_URL: ${EOS_MGM_URL:-root://mgm-master.testnet:1094}
      REVA_STORAGE_EOS_LAYOUT: "{{substr 0 1 .Username}}"
      DAV_FILES_NAMESPACE: "/eos/"
      REVA_LDAP_HOSTNAME: 'ldap.testnet'
      REVA_LDAP_PORT: 636
      REVA_LDAP_BIND_PASSWORD: 'admin'
      REVA_LDAP_BIND_DN: 'cn=admin,dc=example,dc=org'
      REVA_LDAP_BASE_DN: 'dc=example,dc=org'
      REVA_LDAP_SCHEMA_UID: 'uid'
      REVA_LDAP_SCHEMA_MAIL: 'mail'
      REVA_LDAP_SCHEMA_DISPLAYNAME: 'displayname'
      LDAP_URI: 'ldap://ldap.testnet'
      LDAP_BINDDN: 'cn=admin,dc=example,dc=org'
      LDAP_BINDPW: 'admin'
      LDAP_BASEDN: 'dc=example,dc=org'

  mgm-master:
    container_name: mgm-master
    image: owncloud/eos-mgm:4.6.5
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: mgm-master.testnet
    networks:
    - testnet
    volumes:
    - ./e/master/var/log/eos:/var/log/eos
    - ./e/master/var/eos/config:/var/eos/config
    - ./e/master/var/eos/ns-queue:/var/eos/ns-queue
    # this volume kills mgm-master during startup
    # - ./e/master/var/eos/md:/var/eos/md
    environment:
      EOS_SET_MASTER: 1

  mq-master:
    container_name: mq-master
    image: owncloud/eos-mq:4.6.5
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: mq-master.testnet
    networks:
    - testnet
    volumes:
    - ./e/master/var/log/eos:/var/log/eos
    - ./e/master/var/eos/config:/var/eos/config
    - ./e/master/var/eos/ns-queue:/var/eos/ns-queue
    environment:
      EOS_SET_MASTER: 1

  fst:
    container_name: fst
    image: owncloud/eos-fst:4.6.5
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: fst.testnet
    networks:
    - testnet
    volumes:
    - ./e/master/var/log/eos:/var/log/eos
    - ./e/disks:/disks
    environment:
      EOS_MGM_URL: "root://mgm-master.testnet"

  quark-1:
    container_name: quark-1
    image: owncloud/eos-qdb:4.6.5
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: quark-1.testnet
    networks:
    - testnet
    volumes:
    - ./e/quark-1/var/lib/quarkdb:/var/lib/quarkdb
    environment:
      EOS_QDB_DIR: "/var/lib/quarkdb/eosns"
      EOS_QDB_PORT: "7777"
      EOS_QDB_MODE: "raft"
      EOS_QDB_CLUSTER_ID: "3d659c1a-e70f-43f0-bed4-941a2ca0765b"
      EOS_QDB_NODES: "quark-1.testnet:7777,quark-2.testnet:7777,quark-3.testnet:7777"

  quark-2:
    container_name: quark-2
    image: owncloud/eos-qdb:4.6.5
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: quark-2.testnet
    networks:
    - testnet
    volumes:
    - ./e/quark-2/var/lib/quarkdb:/var/lib/quarkdb
    environment:
      EOS_QDB_DIR: "/var/lib/quarkdb/eosns"
      EOS_QDB_PORT: "7777"
      EOS_QDB_MODE: "raft"
      EOS_QDB_CLUSTER_ID: "3d659c1a-e70f-43f0-bed4-941a2ca0765b"
      EOS_QDB_NODES: "quark-1.testnet:7777,quark-2.testnet:7777,quark-3.testnet:7777"

  quark-3:
    container_name: quark-3
    image: owncloud/eos-qdb:4.6.5
    tty: true
    privileged: true
    stdin_open: true
    env_file:
    - ./config/eos-docker.env
    hostname: quark-3.testnet
    networks:
    - testnet
    volumes:
    - ./e/quark-3/var/lib/quarkdb:/var/lib/quarkdb
    environment:
      EOS_QDB_DIR: "/var/lib/quarkdb/eosns"
      EOS_QDB_PORT: "7777"
      EOS_QDB_MODE: "raft"
      EOS_QDB_CLUSTER_ID: "3d659c1a-e70f-43f0-bed4-941a2ca0765b"
      EOS_QDB_NODES: "quark-1.testnet:7777,quark-2.testnet:7777,quark-3.testnet:7777"
